spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/passenger_db
    username: username
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: db/changelog/main-changelog.xml
    enabled: true
server:
  port: 7001

---
spring.config.activate.on-profile: docker
server.port: 8080