spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rating_db
    username: username
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: db/changelog/main-changelog.xml
    enabled: true


  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: rating-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.value.default.type: com.modsen.taxi.ratingservice.dto.RatingRequest




server:
  port: 7004

ratingservice:
  urls:
    passenger: http://localhost:7001/api/v1/passengers/
    driver: http://localhost:7002/api/v1/drivers/

---
spring:
  config:
    activate:
      on-profile: docker
  kafka:
    bootstrap-servers: kafka:9092
server.port: 8080
ratingservice:
  urls:
    passenger: http://passenger:8080/api/v1/passengers/
    driver: http://driver:8080/api/v1/drivers/